[workspace]
channels = ["conda-forge"]
name = "dm-vio"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
suitesparse = ">=7.10.1,<8"
eigen = ">=3.4.0,<4"
yaml-cpp = ">=0.8.0,<0.9"
cmake = ">=4.1.2,<5"
cxx-compiler = ">=1.11.0,<2"
tbb-devel = ">=2022.3.0,<2023"
libopencv = ">=4.12.0,<5"
libboost-devel = "<1.90"
ninja = ">=1.13.2,<2"
ccache = ">=4.12.2,<5"
libzip = ">=1.11.2,<2"
libopengl-devel = ">=1.7.0,<2"
libglx = ">=1.7.0,<2"
libglx-devel = ">=1.7.0,<2"
libgl-devel = ">=1.7.0,<2"
glew = ">=2.3.0,<3"
ffmpeg = ">=8.0.1,<9"
